/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppPlansRouteImport } from './routes/_app.plans'
import { Route as AppModulesRouteImport } from './routes/_app.modules'
import { Route as AppSubscribersIndexRouteImport } from './routes/_app.subscribers.index'
import { Route as AppSubscribersNewRouteImport } from './routes/_app.subscribers.new'
import { Route as AppSubscribersIdRouteImport } from './routes/_app.subscribers.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPlansRoute = AppPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AppRoute,
} as any)
const AppModulesRoute = AppModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscribersIndexRoute = AppSubscribersIndexRouteImport.update({
  id: '/subscribers/',
  path: '/subscribers/',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscribersNewRoute = AppSubscribersNewRouteImport.update({
  id: '/subscribers/new',
  path: '/subscribers/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscribersIdRoute = AppSubscribersIdRouteImport.update({
  id: '/subscribers/$id',
  path: '/subscribers/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/modules': typeof AppModulesRoute
  '/plans': typeof AppPlansRoute
  '/subscribers/$id': typeof AppSubscribersIdRoute
  '/subscribers/new': typeof AppSubscribersNewRoute
  '/subscribers/': typeof AppSubscribersIndexRoute
}
export interface FileRoutesByTo {
  '/modules': typeof AppModulesRoute
  '/plans': typeof AppPlansRoute
  '/': typeof AppIndexRoute
  '/subscribers/$id': typeof AppSubscribersIdRoute
  '/subscribers/new': typeof AppSubscribersNewRoute
  '/subscribers': typeof AppSubscribersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/modules': typeof AppModulesRoute
  '/_app/plans': typeof AppPlansRoute
  '/_app/': typeof AppIndexRoute
  '/_app/subscribers/$id': typeof AppSubscribersIdRoute
  '/_app/subscribers/new': typeof AppSubscribersNewRoute
  '/_app/subscribers/': typeof AppSubscribersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/modules'
    | '/plans'
    | '/subscribers/$id'
    | '/subscribers/new'
    | '/subscribers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/modules'
    | '/plans'
    | '/'
    | '/subscribers/$id'
    | '/subscribers/new'
    | '/subscribers'
  id:
    | '__root__'
    | '/_app'
    | '/_app/modules'
    | '/_app/plans'
    | '/_app/'
    | '/_app/subscribers/$id'
    | '/_app/subscribers/new'
    | '/_app/subscribers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plans': {
      id: '/_app/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AppPlansRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/modules': {
      id: '/_app/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof AppModulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subscribers/': {
      id: '/_app/subscribers/'
      path: '/subscribers'
      fullPath: '/subscribers/'
      preLoaderRoute: typeof AppSubscribersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subscribers/new': {
      id: '/_app/subscribers/new'
      path: '/subscribers/new'
      fullPath: '/subscribers/new'
      preLoaderRoute: typeof AppSubscribersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subscribers/$id': {
      id: '/_app/subscribers/$id'
      path: '/subscribers/$id'
      fullPath: '/subscribers/$id'
      preLoaderRoute: typeof AppSubscribersIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppModulesRoute: typeof AppModulesRoute
  AppPlansRoute: typeof AppPlansRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSubscribersIdRoute: typeof AppSubscribersIdRoute
  AppSubscribersNewRoute: typeof AppSubscribersNewRoute
  AppSubscribersIndexRoute: typeof AppSubscribersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppModulesRoute: AppModulesRoute,
  AppPlansRoute: AppPlansRoute,
  AppIndexRoute: AppIndexRoute,
  AppSubscribersIdRoute: AppSubscribersIdRoute,
  AppSubscribersNewRoute: AppSubscribersNewRoute,
  AppSubscribersIndexRoute: AppSubscribersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
